blank_issues_enabled: false
contact_links:
  - name: Other? Start a discussion
    url: https://github.com/alvy023/texture-surprise/discussions
    about: Please use an issue template for any bugs or feature requests. Other discussions are welcome here.